apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    email: sebastian@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
    - dns01:
        route53:
          region: us-east-1   # AWS region
          role: arn:aws:iam::075948657693:role/eksctl-testcluster-addon-iamserviceaccount-de-Role1-NdWTLAzLhsIj
