name: 'Helm Deploy'

on:
  push:
    branches: [ "main" ]
    paths:
    - 'helm/**'
  workflow_dispatch:

jobs:
  helm_upgrade_dev:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Helm deploy
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm upgrade --install gateway -n gateway ingress-nginx/ingress-nginx