name: Repository Dispatch Trigger

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message from client_payload
        run: echo "Message: ${{ github.event.client_payload.message }}"
