name: Repository Dispatch Trigger

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Repository Dispatch triggered!"
