name: Repository Dispatch Trigger

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch from client payload
        run: |
          if [ "${{ github.event.client_payload.branch }}" != "test-trigger-feature" ]; then
            echo "This workflow only runs on the main branch."
            exit 1
          fi
      - name: Proceed with build
        run: echo "Repository Dispatch Event Triggered on the test-trigger-feature branch"
