name: Repository Dispatch Trigger

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message from client_payload
        run: |
          echo "The env is ${{ github.event.client_payload.env }}"
          echo "The tag is ${{ github.event.client_payload.tag }}"
