# .github/workflows/workflow-b.yml
name: Workflow B

on:
  workflow_run:
    workflows: ["Repository Dispatch Trigger"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env
      - name: Download tag artifact
        uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Run some task for Workflow B
        run: |
          env=$(cat env.txt)
          tag=$(cat tag.txt)
          echo "Env: $env"
          echo "Tag: $tag"
