# .github/workflows/workflow-b.yml
name: Workflow B

on:
  workflow_run:
    workflows: ["Repository Dispatch Trigger"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: trigger.yml
      - name: Run some task for Workflow B
        run: |
          env=$(cat env.txt)
          tag=$(cat tag.txt)
          echo "Env: $env"
          echo "Tag: $tag"
