# .github/workflows/workflow-b.yml
name: Workflow B

on:
  workflow_run:
    workflows: ["Repository Dispatch Trigger"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run some task for Workflow B
        run: |
          echo "Workflow B is now running! echo $env and echo $tag"
          echo "Environment: ${{ github.event.workflow_run.head_commit.message }}
          echo "Tag: ${{ github.event.workflow_run.head_commit.message }}"
