name: Repository Dispatch Trigger

on:
  repository_dispatch:
    types: [trigger-action]

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "Repository Dispatch Event triggered!"
